name: Linter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies and run linters
      run: |
        python -m pip install --upgrade pip pre-commit
        echo """
        repos:
          - repo: https://github.com/pre-commit/mirrors-prettier
            rev: v2.7.1
            hooks:
              - id: prettier
                types_of: [markdown]
        """ > .pre-commit-config.yaml
        pre-commit install 
        pre-commit run --all-files || true
    - name: Add and push files into github
      run: (git add README.md || true) && git commit -m "Lint" && git push
